/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Com.pharmacy.view;

import Com.pharmacy.common.DBConnection;
import Com.pharmacy.controller.ProductDAO;
import Com.pharmacy.model.product;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sushil Shrestha
 */
public class AddProduct extends javax.swing.JFrame {
DefaultTableModel model;
ArrayList name=new ArrayList();
/**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        databasenama();
    }
    
    private void clearFields() {
        jTextField_name.setText("");
        jTextField_rate.setText("");
        jTextField_qty.setText("");
        
        jComboBox_month.setSelectedItem("January");
        jComboBox_year.setSelectedItem("2017");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton_back = new javax.swing.JButton();
        jComboBox_year = new javax.swing.JComboBox();
        jTextField_name = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField_qty = new javax.swing.JTextField();
        jTextField_rate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_month = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Expiry date");

        jButton_back.setBackground(new java.awt.Color(0, 0, 0));
        jButton_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        jComboBox_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });

        jLabel21.setText("Data Entry");

        jTextField_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_qtyKeyTyped(evt);
            }
        });

        jTextField_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rateActionPerformed(evt);
            }
        });
        jTextField_rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_rateKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Existing product will be shown.");

        jLabel1.setText("Name");

        jComboBox_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        jComboBox_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_monthActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity");

        jLabel3.setText("Rate");

        jButton_add.setBackground(new java.awt.Color(0, 0, 0));
        jButton_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus (1).png"))); // NOI18N
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_rate)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jComboBox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_qty)
                                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_monthActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        if(jTextField_name.getText().equals("")||jTextField_rate.getText().equals("")||jTextField_qty.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter complete detail about the drug first");
        }else{
        
            String name=jTextField_name.getText();
        double rate =Double.parseDouble(jTextField_rate.getText());
        int qty=Integer.parseInt(jTextField_qty.getText() );
        String exp_month=jComboBox_month.getSelectedItem().toString();
        String exp_year=jComboBox_year.getSelectedItem().toString();
        
        
        
        product ob=new product();
        ob.setName(name);
        ob.setRate(rate);
        ob.setQty(qty);
        ob.setExp_month(exp_month);
        ob.setExp_year(exp_year);
        if(exp_month.equals("Jan"))
        {
            exp_month="1";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("Feb"))
        {
            exp_month="2";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("March"))
        {
            exp_month="3";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("April"))
            {
            exp_month="4";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("May"))
         {
            exp_month="5";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("June"))
            {
            exp_month="6";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("July"))
            {
            exp_month="7";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("Aug"))
         {
            exp_month="8";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("Sept"))
            {
            exp_month="9";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("Oct"))
         {
            exp_month="10";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("Nov"))
            {
            exp_month="11";
            ob.setSample_month(Integer.parseInt(exp_month));
        }
        else if(exp_month.equals("Dec"))
         {
            exp_month="12";
            ob.setSample_month(Integer.parseInt(exp_month));
        }

//hand over the object to controller class
        ProductDAO pDAO=new ProductDAO();
        pDAO.insertData(ob);
        System.out.println("Added");
        //clear all fields
        clearFields();
        JOptionPane.showMessageDialog(null,"Drug added.");
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        MainframeAdmin m=new MainframeAdmin();
            m.setTitle("Medical Store Management");
            m.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jTextField_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_qtyKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if(!(ch>='0' && ch<='9')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_qtyKeyTyped

    private void jTextField_rateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rateKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if(!(ch>='0' && ch<='9' || ch=='.')){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_rateKeyTyped

    private void jTextField_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rateActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        // TODO add your handling code here:
                // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                jTextField_name.setText(jTextField_name.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                    String txt=jTextField_name.getText();
                    autocomplete(txt);
                    
            }
       
        });
        }
    }//GEN-LAST:event_jTextField_nameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_back;
    private javax.swing.JComboBox jComboBox_month;
    private javax.swing.JComboBox jComboBox_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_qty;
    private javax.swing.JTextField jTextField_rate;
    // End of variables declaration//GEN-END:variables
public void databasenama() {
         
        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from drug";
            Statement st=con.createStatement();
            if(con!=null)
            {
                System.out.println("Connection Sucessful");
            }
            else
                System.out.println("Connection failed");
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                String nama=rs.getString("name");
                 
                name.add(nama);
            }
            rs.close();
                    
            con.close();
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }


         }
    public void autocomplete(String txt){
        String complete= " ";
        int start=txt.length();
        int last=txt.length();
        int a;
        for(a=0;a<name.size();a++){
            if(name.get(a).toString().startsWith(txt)){
                complete=name.get(a).toString();
                last=complete.length();
                break;
            }
    }
        if(last>start){
            jTextField_name.setText(complete);
            jTextField_name.setCaretPosition(last);
            jTextField_name.moveCaretPosition(start);
        }
        
    }
    
}

