/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Com.pharmacy.view;

import Com.pharmacy.common.DBConnection;
import Com.pharmacy.controller.ProductDAO;
import Com.pharmacy.model.product;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sushil Shrestha
 */
public class DeleteDrug extends javax.swing.JFrame {
ArrayList name=new ArrayList();
//int id;
    /**
     * Creates new form DeleteDrug
     */
    public DeleteDrug() {
        initComponents();
        databasenama();
    }
private void clearFields() {
        jTextField_name.setText("Search for drug you want to delete");
        jTextField_rate.setText("");
        jTextField_qty.setText("");
        jTextField_id.setText("");
        jTextField_month.setText("");
        jTextField_year.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_everything = new javax.swing.JButton();
        jTextField_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton_zero = new javax.swing.JButton();
        jTextField_year = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_delete = new javax.swing.JButton();
        jTextField_qty = new javax.swing.JTextField();
        jTextField_month = new javax.swing.JTextField();
        jButton_cancel = new javax.swing.JButton();
        jTextField_rate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Quantity");

        jLabel5.setText("Expiry Date");

        jLabel1.setText("Id");

        jButton_everything.setBackground(new java.awt.Color(0, 0, 0));
        jButton_everything.setForeground(new java.awt.Color(255, 255, 255));
        jButton_everything.setText("Delete");
        jButton_everything.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_everythingActionPerformed(evt);
            }
        });

        jLabel8.setText("Delete EVERYTHING:");

        jButton_zero.setBackground(new java.awt.Color(0, 0, 0));
        jButton_zero.setForeground(new java.awt.Color(255, 255, 255));
        jButton_zero.setText("Delete");
        jButton_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_zeroActionPerformed(evt);
            }
        });

        jTextField_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_yearActionPerformed(evt);
            }
        });

        jTextField_name.setText("Search for drug you want to delete");
        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });

        jLabel3.setText("Rate");

        jLabel6.setText("Delete all items with 0(ZERO) quantity:");

        jLabel2.setText("Name");

        jButton_delete.setBackground(new java.awt.Color(0, 0, 0));
        jButton_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jTextField_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_monthActionPerformed(evt);
            }
        });

        jButton_cancel.setBackground(new java.awt.Color(0, 0, 0));
        jButton_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6))
                            .addGap(66, 66, 66)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_zero)
                                .addComponent(jButton_everything))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addGap(10, 10, 10)
                            .addComponent(jTextField_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_month, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton_delete))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jButton_everything, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton_cancel)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                jTextField_name.setText(jTextField_name.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                    String txt=jTextField_name.getText();
                    autocomplete(txt);
                    
            }
       
        });
        }
        
    }//GEN-LAST:event_jTextField_nameKeyPressed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
        MainframeAdmin m=new MainframeAdmin();
            m.setTitle("Medical Store Management");
            m.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String tname=jTextField_name.getText();
        if(!tname.equals("")){
         

        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from drug where name=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,tname);
            ResultSet rs=pst.executeQuery();
            while (rs.next()) {
                
                jTextField_id.setText(rs.getString(1));
                jTextField_qty.setText(rs.getString(4));
                jTextField_rate.setText(rs.getString(3));
                jTextField_month.setText(rs.getString(5));
                jTextField_year.setText(rs.getString(6));
         
            }
            con.close();
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        }
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextField_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_monthActionPerformed

    private void jTextField_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_yearActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        String tname=jTextField_name.getText();
        if(jTextField_month.getText().equals("")||jTextField_year.getText().equals("")||jTextField_id.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No data to delete!!!!");
        }else{
        int p=JOptionPane.showConfirmDialog(null,"Do you really want to delete the selected drug?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0){
            
            
            try{
                Connection con=DBConnection.getConnection();
                //String sql="delete from product where id="+ob.getId()+"";
                String sql="delete from drug where name=?";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,tname);
                pst.executeUpdate();
                con.close();
            
            } catch (Exception ex) {
                System.out.println(ex);
            }
        clearFields();
        }
        
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_zeroActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null,"Do you really want to delete drugs with ZERO quantity if any?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0){
            
            
            try{
                Connection con=DBConnection.getConnection();
                //String sql="delete from product where id="+ob.getId()+"";
                String sql="delete from drug where qty=0";
                
                PreparedStatement pst=con.prepareStatement(sql);
                
                pst.executeUpdate();
                con.close();
            
            } catch (Exception ex) {
                System.out.println(ex);
            }
        clearFields();
        JOptionPane.showMessageDialog(null,"Deleted Successfully");
        }
    }//GEN-LAST:event_jButton_zeroActionPerformed

    private void jButton_everythingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_everythingActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null,"WARNING!!! Do you want to delete all the details?","Delete",JOptionPane.YES_NO_OPTION);
        if (p==0){
            
            
            try{
                Connection con=DBConnection.getConnection();
                //String sql="delete from product where id="+ob.getId()+"";
                String sql="delete from drug";
                
                PreparedStatement pst=con.prepareStatement(sql);
                
                pst.executeUpdate();
                con.close();
            
            } catch (Exception ex) {
                System.out.println(ex);
            }
        clearFields();
        JOptionPane.showMessageDialog(null,"Deleted Successfully");
        }
    }//GEN-LAST:event_jButton_everythingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDrug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDrug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDrug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDrug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteDrug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_everything;
    private javax.swing.JButton jButton_zero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_month;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_qty;
    private javax.swing.JTextField jTextField_rate;
    private javax.swing.JTextField jTextField_year;
    // End of variables declaration//GEN-END:variables
    public void databasenama() {
         
        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from drug";
            Statement st=con.createStatement();
            if(con!=null)
            {
                System.out.println("Connection Sucessful");
            }
            else
                System.out.println("Connection failed");
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                String nama=rs.getString("name");
                 
                name.add(nama);
            }
            rs.close();
                    
            con.close();
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }


         }
    public void autocomplete(String txt){
        String complete= " ";
        int start=txt.length();
        int last=txt.length();
        int a;
        for(a=0;a<name.size();a++){
            if(name.get(a).toString().startsWith(txt)){
                complete=name.get(a).toString();
                last=complete.length();
                break;
            }
    }
        if(last>start){
            jTextField_name.setText(complete);
            jTextField_name.setCaretPosition(last);
            jTextField_name.moveCaretPosition(start);
        }
        
    }
        
}
