/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Com.pharmacy.view;
//package Com.example.view;

import Com.pharmacy.common.TrackUser;
import Com.pharmacy.common.backupdb;
import Com.pharmacy.common.databaseTest;
import Com.pharmacy.common.licenseFile;
import Com.pharmacy.controller.LoginDAO;
import Com.pharmacy.model.Login;

import java.awt.Font;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sushil Shrestha
 */
public class LoginUser extends javax.swing.JFrame {

	/**
	 * Creates new form login
	 */
	public LoginUser() {
		// try{
		// Properties prop= new Properties();
		// prop.load(this.getClass().getClassLoader().getResourceAsStream("f://license.properties"));
		// }catch(Exception es){
		// es.printStackTrace();
		// }

		// try{
		//
		//
		//
		// Properties prop = new Properties();
		// String fileName = "f://license.properties";
		// InputStream is = new FileInputStream(fileName);
		//
		// if(is!=null){
		// prop.load(is);
		// System.out.println("here");
		// System.out.println(prop.getProperty("code"));
		// System.exit(0);
		// }else{
		//
		// initComponents();
		// }
		//
		//
		// }catch(Exception ex){
		// ex.printStackTrace();
		// }
		//
		//
		//
		//
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jButton_ok = new javax.swing.JButton();
		jPasswordField_password = new javax.swing.JPasswordField();
		jLabel1 = new javax.swing.JLabel();
		jTextField_username = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(204, 204, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sushil Shrestha\\Desktop\\Guest Male_64px.png")); // NOI18N

		jButton1.setBackground(new java.awt.Color(0, 0, 0));
		jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sushil Shrestha\\Desktop\\Syringe_32px.png")); // NOI18N
		jButton1.setText(
				"ORCHID PHARMACY                                                                                  ");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton_ok.setBackground(new java.awt.Color(0, 0, 0));
		jButton_ok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jButton_ok.setForeground(new java.awt.Color(255, 255, 255));
		jButton_ok.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sushil Shrestha\\Desktop\\Double Right_48px.png")); // NOI18N
		jButton_ok.setText("GO");
		jButton_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_okActionPerformed(evt);
			}
		});

		jPasswordField_password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField_passwordActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 0, 255));
		jLabel1.setText("Sign in");

		jTextField_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_username.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_usernameActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 328,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE,
												178, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 178,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton_ok).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(26, 26, 26).addComponent(jButton1)
						.addGap(54, 54, 54).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
						.addComponent(jButton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(81, 81, 81)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(34, Short.MAX_VALUE)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(33, 33, 33)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(41, 41, 41)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(40, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_okActionPerformed
		// TODO add your handling code here:
		String uname = jTextField_username.getText();
		String pwd = new String(jPasswordField_password.getPassword());

		// set these values to model class login
		Login ob = new Login();

		ob.setUsername(uname);
		ob.setPassword(pwd);
		// hand over this object to controller class
		LoginDAO loginDAO = new LoginDAO();
		int x = loginDAO.validateUser(ob);
		if (x == 0) {
			JOptionPane.showMessageDialog(null, "Invalid Username or password...");
			jTextField_username.setText("");
			jPasswordField_password.setText("");

		} else {
			JOptionPane.showMessageDialog(null, "Login Success...");
			this.dispose();

			backupdb.backup();

			MainframeAdmin m = new MainframeAdmin();
			m.setTitle("Medical Store Management");
			m.setVisible(true);
			

		}
	}// GEN-LAST:event_jButton_okActionPerformed

	private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordField_passwordActionPerformed

	}// GEN-LAST:event_jPasswordField_passwordActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_usernameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_usernameActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				LoginUser h = new LoginUser();
				databaseTest db = new databaseTest();
				boolean a = db.checkForDb();
				if (a == true) {
					h.setTitle("Login to the system");
					h.setVisible(true);
				} else {

				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton_ok;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField_password;
	private javax.swing.JTextField jTextField_username;
	// End of variables declaration//GEN-END:variables
}
