/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Com.pharmacy.view;

import Com.pharmacy.controller.billDAO;
import Com.pharmacy.common.DBConnection;
import Com.pharmacy.common.TrackUser;
import Com.pharmacy.controller.ProductDAO;
import Com.pharmacy.controller.salesDAO;
import Com.pharmacy.model.bill;
import Com.pharmacy.model.product;
import Com.pharmacy.model.sales;
import java.awt.*;
import java.awt.event.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sushil Shrestha
 */
public class MainframeAdmin extends javax.swing.JFrame {
	DefaultTableModel model;
	ArrayList name = new ArrayList();
	int j = 0;
	int z = 0;
	double u = 0;
	double y = 0;

	/**
	 * 
	 * Creates new form mainframe
	 */
	public MainframeAdmin() {
		initComponents();
		databasenama();
		model = new DefaultTableModel(null,
				new Object[] { "S.N.", " Drug Name", "Expiry Date", "", "Quantity", "Rate", "Amount" });
		// set this object to jTable_Product
		jTable_admin.setModel(model);
		jLabel_username.setText("Logged in as " + TrackUser.uname);
		Date today = new Date();
		jLabel_date.setText(today.toString());
		jTextField_discount.setText("0");
	}

	public void printBill() {
		/*
		 * String str="Namaste Super Market\nSinamangal,Kathmandu\n\n\n";
		 * 
		 * int rowCount=jTable_admin.getRowCount(); for(int i=0;i<rowCount;i++){
		 * str+=model.getValueAt(i, 0)+" "; str+=model.getValueAt(i, 1)+" ";
		 * str+=model.getValueAt(i, 3)+" "; str+=model.getValueAt(i, 4)+"\n"; }
		 * str+="Grand Total: "+jLabel_grandtotal.getText();
		 * str+="\nThank You for visiting us!!!!!!!!!!!!";
		 */
		BillPrint ob = new BillPrint();
		/*
		 * ob.jTextArea_Bill.setLineWrap(true); ob.jTextArea_Bill.setText(str); try{
		 * ob.jTextArea_Bill.print();
		 * 
		 * }catch(Exception ex){ System.out.println(ex); }
		 */

	}

	public void clearTableRow() {
		int count = jTable_admin.getRowCount();
		for (int i = 0; i < count; i++) {
			model.removeRow(0);
		}

	}

	private void clearFields() {
		jTextField_name.setText("");
		jTextField_rate.setText("");
		jTextField_qty.setText("");
		jTextField_amount.setText("");
		jTextField_available.setText("");
		jTextField_month.setText("");
		jTextField_year.setText("");
	}

	private void createTable() {
		int rowCount = jTable_admin.getRowCount();
		for (int i = 0; i < rowCount; i++) {
			model.removeRow(0);
		}
	}

	private void computeTotal() {
		int rowCount = jTable_admin.getRowCount();
		double gTotal = 0;
		for (int i = 0; i < rowCount; i++) {
			double total = Double.parseDouble(jTable_admin.getValueAt(i, 6).toString());
			gTotal += total;
		}
		jLabel_total.setText(gTotal + "");
	}

	/*
	 * private void loadData(){ createTable(); ProductDAO pDAO=new ProductDAO();
	 * ArrayList<product> list=pDAO.fetchData(); for(int i=0;i<list.size();i++) {
	 * model.addRow(new
	 * Object[]{list.get(i).getName(),list.get(i).getRate(),list.get(i).getQty(),
	 * list.get(i).getExp_month(),list.get(i).getExp_year()}); } }
	 */
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jTextField_available = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField_amount = new javax.swing.JTextField();
		jButton_add = new javax.swing.JButton();
		jTextField_rate = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField_year = new javax.swing.JTextField();
		jTextField_qty = new javax.swing.JTextField();
		jTextField_month = new javax.swing.JTextField();
		jTextField_name = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jButton_additem = new javax.swing.JButton();
		jButton_exit = new javax.swing.JButton();
		jButton_update = new javax.swing.JButton();
		jButton_date = new javax.swing.JButton();
		jButton_delete = new javax.swing.JButton();
		jButton_stock = new javax.swing.JButton();
		jButton_logout = new javax.swing.JButton();
		jButton_bill = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel_grandtotal = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jButton_total = new javax.swing.JButton();
		jTextField_discount = new javax.swing.JTextField();
		jComboBox_print = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jButton_print = new javax.swing.JButton();
		jLabel_total = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel_date = new javax.swing.JLabel();
		jLabel_username = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextField_billno = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jButton_clear = new javax.swing.JButton();
		jButton_remove = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable_admin = new javax.swing.JTable();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setAlwaysOnTop(true);
		setBackground(new java.awt.Color(38, 168, 234));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setResizable(false);
		addContainerListener(new java.awt.event.ContainerAdapter() {
			public void componentRemoved(java.awt.event.ContainerEvent evt) {
				formComponentRemoved(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(38, 168, 234));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Expiry Date");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Available");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Name");

		jTextField_available.setEditable(false);
		jTextField_available.setBackground(new java.awt.Color(204, 204, 204));

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("Amount");

		jTextField_amount.setEditable(false);
		jTextField_amount.setBackground(new java.awt.Color(204, 204, 204));
		jTextField_amount.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_amountActionPerformed(evt);
			}
		});

		jButton_add.setBackground(new java.awt.Color(0, 0, 0));
		jButton_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jButton_add.setForeground(new java.awt.Color(255, 255, 255));
		jButton_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart.png"))); // NOI18N
		jButton_add.setText("ADD");
		jButton_add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_addActionPerformed(evt);
			}
		});

		jTextField_rate.setEditable(false);
		jTextField_rate.setBackground(new java.awt.Color(204, 204, 204));
		jTextField_rate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_rateActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Rate");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Quantity");

		jTextField_year.setEditable(false);
		jTextField_year.setBackground(new java.awt.Color(204, 204, 204));

		jTextField_qty.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_qtyActionPerformed(evt);
			}
		});
		jTextField_qty.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField_qtyKeyPressed(evt);
			}

			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField_qtyKeyTyped(evt);
			}
		});

		jTextField_month.setEditable(false);
		jTextField_month.setBackground(new java.awt.Color(204, 204, 204));
		jTextField_month.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_monthActionPerformed(evt);
			}
		});

		jTextField_name.setBackground(new java.awt.Color(204, 204, 204));
		jTextField_name.setText("Enter Product name");
		jTextField_name.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_nameActionPerformed(evt);
			}
		});
		jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField_nameKeyPressed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addGap(10, 10, 10)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1).addComponent(jTextField_name,
												javax.swing.GroupLayout.PREFERRED_SIZE, 139,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jTextField_qty))
								.addGap(33, 33, 33)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jTextField_available).addComponent(jLabel3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGap(34, 34, 34)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel4)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(jTextField_month, javax.swing.GroupLayout.PREFERRED_SIZE,
														63, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE,
														63, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(28, 28, 28)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel5).addComponent(jTextField_rate,
												javax.swing.GroupLayout.PREFERRED_SIZE, 58,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(33, 33, 33)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel6).addComponent(jTextField_amount,
												javax.swing.GroupLayout.PREFERRED_SIZE, 64,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton_add).addGap(44, 44, 44)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1).addComponent(jLabel2).addComponent(jLabel3)
										.addComponent(jLabel4).addComponent(jLabel5)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_available, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_month, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_rate, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(16, Short.MAX_VALUE)));

		jPanel2.setBackground(new java.awt.Color(38, 168, 234));
		jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jButton_additem.setBackground(new java.awt.Color(0, 0, 0));
		jButton_additem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus (1).png"))); // NOI18N
		jButton_additem.setActionCommand("Add");
		jButton_additem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_additemActionPerformed(evt);
			}
		});

		jButton_exit.setBackground(new java.awt.Color(0, 0, 0));
		jButton_exit.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
		jButton_exit.setForeground(new java.awt.Color(128, 0, 0));
		jButton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error.png"))); // NOI18N
		jButton_exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_exitActionPerformed(evt);
			}
		});

		jButton_update.setBackground(new java.awt.Color(0, 0, 0));
		jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
		jButton_update.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_updateActionPerformed(evt);
			}
		});

		jButton_date.setBackground(new java.awt.Color(0, 0, 0));
		jButton_date.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list.png"))); // NOI18N
		jButton_date.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_dateActionPerformed(evt);
			}
		});

		jButton_delete.setBackground(new java.awt.Color(0, 0, 0));
		jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
		jButton_delete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_deleteActionPerformed(evt);
			}
		});

		jButton_stock.setBackground(new java.awt.Color(0, 0, 0));
		jButton_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books.png"))); // NOI18N
		jButton_stock.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_stockActionPerformed(evt);
			}
		});

		jButton_logout.setBackground(new java.awt.Color(0, 0, 0));
		jButton_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
		jButton_logout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_logoutActionPerformed(evt);
			}
		});

		jButton_bill.setBackground(new java.awt.Color(0, 0, 0));
		jButton_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/invoice.png"))); // NOI18N
		jButton_bill.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_billActionPerformed(evt);
			}
		});

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel12.setForeground(new java.awt.Color(240, 240, 240));
		jLabel12.setText("LOGOUT");

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(240, 240, 240));
		jLabel13.setText("EXIT");

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(240, 240, 240));
		jLabel14.setText("  ADD ITEM");

		jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel17.setForeground(new java.awt.Color(240, 240, 240));
		jLabel17.setText("CHECK EXP_DATE");

		jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel18.setForeground(new java.awt.Color(240, 240, 240));
		jLabel18.setText("VIEW BILLS");

		jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(240, 240, 240));
		jLabel19.setText("UPDATE");

		jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel24.setForeground(new java.awt.Color(240, 240, 240));
		jLabel24.setText("  DELETE ITEM");

		jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel25.setForeground(new java.awt.Color(240, 240, 240));
		jLabel25.setText("   VIEW STOCK");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(42, 42, 42)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_additem))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(9, 9, 9).addComponent(jLabel24,
										javax.swing.GroupLayout.PREFERRED_SIZE, 78,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18)
										.addComponent(jButton_delete)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(
										jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout
										.createSequentialGroup().addGap(32, 32, 32).addComponent(jButton_stock)))
						.addGap(33, 33, 33)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton_bill).addComponent(jLabel18))
						.addGap(34, 34, 34)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel2Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel19))
								.addComponent(jButton_update))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(35, 35, 35)
										.addComponent(jButton_date))
								.addGroup(jPanel2Layout
										.createSequentialGroup().addGap(24, 24, 24).addComponent(jLabel17)))
						.addGap(59, 59, 59)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton_logout, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 55,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel2Layout
										.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel12)))
						.addGap(26, 26, 26)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(10, 10, 10)
										.addComponent(jLabel13)))
						.addGap(72, 72, 72)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jButton_exit, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(6, 6, Short.MAX_VALUE)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18))
								.addGroup(jPanel2Layout.createSequentialGroup()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jButton_additem, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton_delete, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton_stock, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton_bill, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton_update, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton_date, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()))));

		jPanel3.setBackground(new java.awt.Color(38, 168, 234));

		jLabel_grandtotal.setText(" ");

		jLabel10.setText("%");

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("Grand Total");

		jButton_total.setBackground(new java.awt.Color(0, 0, 0));
		jButton_total.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator.png"))); // NOI18N
		jButton_total.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_totalActionPerformed(evt);
			}
		});

		jTextField_discount.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField_discountActionPerformed(evt);
			}
		});
		jTextField_discount.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField_discountKeyTyped(evt);
			}
		});

		jComboBox_print.setBackground(new java.awt.Color(0, 0, 0));
		jComboBox_print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jComboBox_print.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Print Bill", "View Bill" }));
		jComboBox_print.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_printActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("Total");

		jButton_print.setBackground(new java.awt.Color(0, 0, 0));
		jButton_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/invoice (1).png"))); // NOI18N
		jButton_print.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_printActionPerformed(evt);
			}
		});

		jLabel_total.setText(" ");

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("Discount");

		jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel22.setForeground(new java.awt.Color(255, 255, 255));
		jLabel22.setText("CALCULATE");

		jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel23.setForeground(new java.awt.Color(255, 255, 255));
		jLabel23.setText("GO TO BILLING");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel3Layout.createSequentialGroup()
														.addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel_total,
																javax.swing.GroupLayout.PREFERRED_SIZE, 67,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
																jPanel3Layout.createSequentialGroup().addComponent(
																		jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
																		56, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(0, 0, Short.MAX_VALUE))
														.addGroup(jPanel3Layout.createSequentialGroup()
																.addGap(0, 0, Short.MAX_VALUE)
																.addGroup(jPanel3Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(jLabel11)
																		.addGroup(jPanel3Layout.createSequentialGroup()
																				.addComponent(jLabel7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						57,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(10, 10, 10)))))
														.addGap(18, 18, 18)
														.addGroup(jPanel3Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addGroup(jPanel3Layout.createSequentialGroup()
																		.addComponent(jTextField_discount,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				26,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jLabel10))
																.addComponent(jLabel_grandtotal,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 68,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel3Layout.createSequentialGroup()
																.addGap(19, 19, 19).addComponent(jButton_total,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 52,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(jPanel3Layout.createSequentialGroup()
																.addGap(18, 18, 18)
																.addGroup(jPanel3Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jButton_print,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				57,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel22))))
												.addGap(36, 36, 36))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup()
												.addComponent(jComboBox_print, javax.swing.GroupLayout.PREFERRED_SIZE,
														143, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jLabel23).addGap(26, 26, 26)))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(
										jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel_total, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jTextField_discount,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
												.addComponent(jLabel10))
										.addGap(13, 13, 13)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel_grandtotal).addComponent(jLabel11)
												.addComponent(jLabel22)))
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(19, 19, 19).addComponent(
										jButton_total, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(jButton_print, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel23))
								.addComponent(jComboBox_print, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(19, Short.MAX_VALUE)));

		jPanel4.setBackground(new java.awt.Color(0, 124, 192));

		jLabel_date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel_date.setForeground(new java.awt.Color(240, 240, 240));
		jLabel_date.setText("date");

		jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel_username.setForeground(new java.awt.Color(240, 240, 240));
		jLabel_username.setText("Username");

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(240, 240, 240));
		jLabel8.setText("Bill No.");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addGap(504, 504, 504).addComponent(jLabel8)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTextField_billno, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel_date, javax.swing.GroupLayout.PREFERRED_SIZE,
										169, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 216,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel_username).addComponent(jLabel8)
								.addComponent(jTextField_billno, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_date))
						.addContainerGap()));

		jPanel5.setBackground(new java.awt.Color(0, 124, 192));

		jButton_clear.setBackground(new java.awt.Color(0, 0, 0));
		jButton_clear.setForeground(new java.awt.Color(255, 255, 255));
		jButton_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eraser.png"))); // NOI18N
		jButton_clear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_clearActionPerformed(evt);
			}
		});

		jButton_remove.setBackground(new java.awt.Color(0, 0, 0));
		jButton_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
		jButton_remove.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_removeActionPerformed(evt);
			}
		});

		jTable_admin.setBackground(new java.awt.Color(204, 204, 204));
		jTable_admin.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] {

		}));
		jScrollPane1.setViewportView(jTable_admin);

		jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setText("REMOVE ITEM");

		jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(255, 255, 255));
		jLabel21.setText("  CLEAR TABLE");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel5Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jButton_remove, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton_clear, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addComponent(jLabel20).addComponent(jLabel21))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel20)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel21)
						.addGap(45, 45, 45))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
						.addContainerGap(12, Short.MAX_VALUE).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(52, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(48, 48, 48)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(16, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formComponentRemoved(java.awt.event.ContainerEvent evt) {// GEN-FIRST:event_formComponentRemoved
		// TODO add your handling code here:
	}// GEN-LAST:event_formComponentRemoved

	private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_nameActionPerformed
		// TODO add your handling code here:
		String tname = jTextField_name.getText();
		if (!tname.equals("")) {

			try {
				Connection con = DBConnection.getConnection();
				String sql = "select * from drug where name=? and qty>0";
				PreparedStatement pst = con.prepareStatement(sql);
				pst.setString(1, tname);
				ResultSet rs = pst.executeQuery();
				while (rs.next()) {

					// jTextField_id.setText(rs.getString(1));
					jTextField_available.setText(rs.getString(4));
					jTextField_rate.setText(rs.getString(3));
					jTextField_month.setText(rs.getString(5));
					jTextField_year.setText(rs.getString(6));
					jTextField_amount.setText("0");

				}
				con.close();

			} catch (SQLException ex) {
				System.out.println(ex);
			}
		}
	}// GEN-LAST:event_jTextField_nameActionPerformed

	private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField_nameKeyPressed
		// TODO add your handling code here:
		switch (evt.getKeyCode()) {
		case KeyEvent.VK_BACK_SPACE:
			break;
		case KeyEvent.VK_ENTER:
			jTextField_name.setText(jTextField_name.getText());
			break;
		default:
			EventQueue.invokeLater(new Runnable() {

				@Override
				public void run() {
					String txt = jTextField_name.getText();
					autocomplete(txt);

				}

			});
		}
	}// GEN-LAST:event_jTextField_nameKeyPressed

	private void jTextField_monthActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_monthActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_monthActionPerformed

	private void jTextField_rateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_rateActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_rateActionPerformed

	private void jTextField_amountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_amountActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_amountActionPerformed

	void loadData1() {
		// createTable();
		salesDAO pDAO = new salesDAO();
		ArrayList<sales> list = pDAO.fetchData();
		// jTextField_billno.setText("123");
		for (int i = 0; i < list.size(); i++)

		{
			int a = list.get(i).getBillno() + 1;
			jTextField_billno.setText(Integer.toString(a));
			// model.addRow(new
			// Object[]{list.get(i).getItem(),list.get(i).getExp_month(),list.get(i).getExp_year(),list.get(i).getQtysold(),list.get(i).getRate(),list.get(i).getAmount()});
			// x =list.get(i).getBillno();
		}
		if (list.size() == 0) {
			jTextField_billno.setText("1");
		}

	}

	private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_addActionPerformed
		// TODO add your handling code here:
		loadData1();
		// jTextField_billno.setText("123");
		String tname = jTextField_name.getText();

		int p = Integer.parseInt(jTextField_qty.getText());

		j = j + 1;

		double q = p * Integer.parseInt(jTextField_rate.getText());
		jTextField_amount.setText(Double.toString(q));
		if (tname.equals("")) {
			JOptionPane.showMessageDialog(null, "No input received.");
		} else {

			ProductDAO pDAO = new ProductDAO();
			ArrayList<product> list = pDAO.fetchDataWithNamesale(tname, p, j);
			for (int i = 0; i < list.size(); i++) {

				model.addRow(new Object[] { (list.get(i).getSN()), list.get(i).getName(), list.get(i).getExp_month(),
						list.get(i).getExp_year(), list.get(i).getSoldno(), list.get(i).getRate(),
						list.get(i).getAmount() });
				computeTotal();

			}
		}
		clearFields();
		if (z != 0) {

		}

		if (jTextField_discount.equals("0")) {
			jLabel_grandtotal = (jLabel_total);
		}

	}// GEN-LAST:event_jButton_addActionPerformed

	private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_clearActionPerformed
		// TODO add your handling code here:\
		DefaultTableModel m = (DefaultTableModel) jTable_admin.getModel();
		while (model.getRowCount() > 0) {
			for (int i = 0; i < model.getRowCount(); i++) {
				model.removeRow(i);
			}
			jLabel_total.setText("0");
			jLabel_grandtotal.setText("0");
			jTextField_discount.setText("0");
		}

	}// GEN-LAST:event_jButton_clearActionPerformed

	private void jTextField_qtyKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField_qtyKeyTyped
		// TODO add your handling code here:
		// TODO add your handling code here:
		char ch = evt.getKeyChar();
		if (!(ch >= '0' && ch <= '9')) {
			evt.consume();
		}
	}// GEN-LAST:event_jTextField_qtyKeyTyped

	private void jTextField_qtyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_qtyActionPerformed
		// TODO add your handling code here:
		int p = Integer.parseInt(jTextField_qty.getText());
		double q = p * Integer.parseInt(jTextField_rate.getText());
		jTextField_amount.setText(Double.toString(q));

	}// GEN-LAST:event_jTextField_qtyActionPerformed

	private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_removeActionPerformed
		// TODO add your handling code here:
		int row = jTable_admin.getSelectedRow();
		model.removeRow(row);
		z = z + 1;
		j = j - 1;
		computeTotal();
	}// GEN-LAST:event_jButton_removeActionPerformed

	private void jTextField_qtyKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField_qtyKeyPressed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField_qtyKeyPressed

	private void jButton_totalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_totalActionPerformed
		// TODO add your handling code here:

		double total = Double.parseDouble(jLabel_total.getText());
		double discount = Double.parseDouble(jTextField_discount.getText());
		double gTotal = total - ((discount / 100) * total);
		jLabel_grandtotal.setText(Double.toString(gTotal));
		u = discount;
		y = gTotal;
	}// GEN-LAST:event_jButton_totalActionPerformed

	private void jTextField_discountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField_discountActionPerformed
		// TODO add your handling code here:
		double total = Double.parseDouble(jLabel_total.getText());
		double discount = Double.parseDouble(jTextField_discount.getText());
		double gTotal = total - ((discount / 100) * total);
		jLabel_grandtotal.setText(Double.toString(gTotal));

	}// GEN-LAST:event_jTextField_discountActionPerformed

	private void jTextField_discountKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField_discountKeyTyped
		// TODO add your handling code here:
		// TODO add your handling code here:
		char ch = evt.getKeyChar();
		if (!(ch >= '0' && ch <= '9')) {
			evt.consume();
		}
	}// GEN-LAST:event_jTextField_discountKeyTyped
	/*
	 * void row() { DefaultTableModel m= (DefaultTableModel)jTable_admin.getModel();
	 * print n=new print();
	 * n.jTextArea1.append("Drug Name\tExpiry Date\t\tQuantity\tRate\tAmount\n");
	 * //model=new DefaultTableModel(null,new Object[]{
	 * "Drug Name","Expiry Date","","Quantity","Rate","Amount"}); for(int
	 * i=0;i<model.getRowCount();i++){ //model.getValueAt(i, 0);
	 * 
	 * 
	 * String item=jTable_admin.getValueAt(i, 1).toString(); String
	 * month=jTable_admin.getValueAt(i, 2).toString(); String
	 * year=jTable_admin.getValueAt(i, 3).toString(); String
	 * qty=jTable_admin.getValueAt(i, 4).toString(); String
	 * rate=jTable_admin.getValueAt(i, 5).toString(); String
	 * amount=jTable_admin.getValueAt(i, 6).toString();
	 * 
	 * n.jTextArea1.append(item+"  "+month+"\t"+year+"\t"+qty+"\t"+rate+"\t"+amount+
	 * "\n");
	 * 
	 * try{ FileWriter writer= new FileWriter("D:\\demo.txt"); try(BufferedWriter w=
	 * new BufferedWriter(writer)){ n.jTextArea1.write(w);
	 * 
	 * } n.jTextArea1.requestFocus(); } catch(Exception e){ System.out.println(e); }
	 * } }
	 */

	private void jButton_printActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_printActionPerformed
		// TODO add your handling code here:
		String choice = jComboBox_print.getSelectedItem().toString();

		double total = Double.parseDouble(jLabel_total.getText());
		String s = jTextField_discount.getText();
		double discount = Double.parseDouble(jTextField_discount.getText());
		double gTotal = total - ((discount / 100) * total);
		BillPrint n = new BillPrint();
		print a = new print();
		n.clearSales();
		a.printtxt(jTextField_billno.getText(), jLabel_date.getText());
		String tableno = jTextField_billno.getText();
		int tp = Integer.parseInt(tableno);
		ArrayList<sales> list = new ArrayList();
		ArrayList<bill> list1 = new ArrayList();
		int count = jTable_admin.getRowCount();
		for (int i = 0; i < count; i++) {
			int sn = Integer.parseInt(model.getValueAt(i, 0).toString());

			String item = model.getValueAt(i, 1).toString();
			int qtysold = Integer.parseInt(model.getValueAt(i, 4).toString());
			String exp_month = model.getValueAt(i, 2).toString();
			String exp_year = model.getValueAt(i, 3).toString();

			double rate = Double.parseDouble(model.getValueAt(i, 5).toString());
			double amount = Double.parseDouble(model.getValueAt(i, 6).toString());
			int sid = TrackUser.uid;
			Date d = new Date();

			// create model class sales object and set these values
			sales ob = new sales();
			ob.setSn(sn);
			ob.setAmount(amount);
			ob.setQtysold(qtysold);
			ob.setItem(item);
			ob.setExp_month(exp_month);
			ob.setExp_year(exp_year);
			ob.setRate(rate);
			ob.setDos(d);
			a.setvalue(item, exp_month, exp_year, Integer.toString(qtysold), Double.toString(rate),
					Double.toString(amount));
			// add this object to list
			list.add(ob);

			// for bill
			bill obj = new bill();
			obj.setBillno(tp);
			obj.setAmount(amount);
			obj.setQtysold(qtysold);
			obj.setItem(item);
			obj.setExp_month(exp_month);
			obj.setExp_year(exp_year);
			obj.setRate(rate);
			obj.setDate(d);
			list1.add(obj);

		}
		// System.out.println("Table cleared");
		a.example(total, s, jLabel_grandtotal.getText());
		salesDAO sDAO = new salesDAO();
		sDAO.insertData(list);
		System.out.println("insertion successfulllllllllllllllllllllllllllllllllllll");
		billDAO bDAO = new billDAO();
		bDAO.insertData(list1);
		System.out.println("insertion in bill");
		// BillPrint n=new BillPrint();

		// n.loadData();
		// n.setVisible(true);
		// printBill();
		this.dispose();
		clearTableRow();

		n.loadData();

		n.computeGrandTotal();
		// n.jLabel_grandtotal=(jLabel_grandtotal);

		n.discount(s, gTotal);

		if (choice.equals("Print Bill")) {
			System.out.println("print bill");
			a.setVisible(true);
			a.setTitle("Print Bill");
			this.dispose();
		} else if (choice.equals("View Bill")) {
			System.out.println("view bill");
			n.setVisible(true);
			n.setTitle("View Bill");
			this.dispose();
		}

		/*
		 * 
		 * //a.jTextArea1.append("Drug Name\tExpiry Date\t\tQuantity\tRate\tAmount\n");
		 * //model=new DefaultTableModel(null,new Object[]{
		 * "Drug Name","Expiry Date","","Quantity","Rate","Amount"}); for(int
		 * i=0;i<model.getRowCount();i++){ //model.getValueAt(i, 0);
		 * 
		 * 
		 * String item=jTable_admin.getValueAt(i, 1).toString(); String
		 * month=jTable_admin.getValueAt(i, 2).toString(); String
		 * year=jTable_admin.getValueAt(i, 3).toString(); String
		 * qty=jTable_admin.getValueAt(i, 4).toString(); String
		 * rate=jTable_admin.getValueAt(i, 5).toString(); String
		 * amount=jTable_admin.getValueAt(i, 6).toString();
		 * 
		 * //
		 * a.jTextArea1.append(item+"  "+month+"\t"+year+"\t"+qty+"\t"+rate+"\t"+amount+
		 * "\n");
		 * 
		 * a.setvalue(item,month,year,qty,rate,amount); }
		 */

	}// GEN-LAST:event_jButton_printActionPerformed

	private void jComboBox_printActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox_printActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox_printActionPerformed

	private void jButton_billActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_billActionPerformed
		// TODO add your handling code here:
		searchBill nn = new searchBill();
		nn.setVisible(true);
		nn.setTitle("View Bill");
		this.dispose();
	}// GEN-LAST:event_jButton_billActionPerformed

	private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_logoutActionPerformed
		// TODO add your handling code here:
		new LoginUser().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton_logoutActionPerformed

	private void jButton_stockActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_stockActionPerformed
		// TODO add your handling code here:
		StockView n = new StockView();
		n.setTitle("Stock");
		n.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_jButton_stockActionPerformed

	private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_deleteActionPerformed
		// TODO add your handling code here:
		DeleteDrug n = new DeleteDrug();
		n.setTitle("Delete Drug");
		n.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_jButton_deleteActionPerformed

	private void jButton_dateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_dateActionPerformed
		// TODO add your handling code here:
		ExpiryCheck n = new ExpiryCheck();
		n.setTitle("EXPIRY DATE CHECK");
		n.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_jButton_dateActionPerformed

	private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_updateActionPerformed
		// TODO add your handling code here:
		Update n = new Update();
		n.setTitle("UPDATE");
		n.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton_updateActionPerformed

	private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_exitActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}// GEN-LAST:event_jButton_exitActionPerformed

	private void jButton_additemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_additemActionPerformed
		// TODO add your handling code here:
		AddProduct n = new AddProduct();
		n.setTitle("Add Drug");
		n.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_jButton_additemActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainframeAdmin().setVisible(true);

			}

		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_add;
	private javax.swing.JButton jButton_additem;
	private javax.swing.JButton jButton_bill;
	private javax.swing.JButton jButton_clear;
	private javax.swing.JButton jButton_date;
	private javax.swing.JButton jButton_delete;
	private javax.swing.JButton jButton_exit;
	private javax.swing.JButton jButton_logout;
	private javax.swing.JButton jButton_print;
	private javax.swing.JButton jButton_remove;
	private javax.swing.JButton jButton_stock;
	private javax.swing.JButton jButton_total;
	private javax.swing.JButton jButton_update;
	private javax.swing.JComboBox jComboBox_print;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabel_date;
	private javax.swing.JLabel jLabel_grandtotal;
	private javax.swing.JLabel jLabel_total;
	private javax.swing.JLabel jLabel_username;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable_admin;
	private javax.swing.JTextField jTextField_amount;
	private javax.swing.JTextField jTextField_available;
	private javax.swing.JTextField jTextField_billno;
	private javax.swing.JTextField jTextField_discount;
	private javax.swing.JTextField jTextField_month;
	private javax.swing.JTextField jTextField_name;
	private javax.swing.JTextField jTextField_qty;
	private javax.swing.JTextField jTextField_rate;
	private javax.swing.JTextField jTextField_year;

	// End of variables declaration//GEN-END:variables
	public void databasenama() {

		try {
			Connection con = DBConnection.getConnection();
			String sql = "select * from drug";
			Statement st = con.createStatement();
			if (con != null) {
				System.out.println("Connection Sucessful");
			} else
				System.out.println("Connection failed");
			ResultSet rs = st.executeQuery(sql);
			while (rs.next()) {
				String nama = rs.getString("name");

				name.add(nama);
			}
			rs.close();

			con.close();

		} catch (SQLException ex) {
			System.out.println(ex);
		}

	}

	public void autocomplete(String txt) {
		String complete = " ";
		int start = txt.length();
		int last = txt.length();
		int a;
		for (a = 0; a < name.size(); a++) {
			if (name.get(a).toString().startsWith(txt)) {
				complete = name.get(a).toString();
				last = complete.length();
				break;
			}
		}
		if (last > start) {
			jTextField_name.setText(complete);
			jTextField_name.setCaretPosition(last);
			jTextField_name.moveCaretPosition(start);
		}

	}
}
