/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Com.pharmacy.view;

import Com.pharmacy.common.DBConnection;
import Com.pharmacy.controller.ProductDAO;
import Com.pharmacy.model.product;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sushil Shrestha
 */
public class Update extends javax.swing.JFrame {
ArrayList name=new ArrayList();
    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        databasenama();
    }
private void clearFields() {
    jTextField_id.setText("");
        jTextField_name.setText("Search for drug you want to delete");
        jTextField_rate.setText("");
        jTextField_quantity.setText("");
        jComboBox_month.setSelectedItem("January");
        jComboBox_year.setSelectedItem("2017"); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_name = new javax.swing.JTextField();
        jLabel_id = new javax.swing.JLabel();
        jButton_update = new javax.swing.JButton();
        jTextField_id = new javax.swing.JTextField();
        jTextField_rate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_month = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_year = new javax.swing.JComboBox();
        jTextField_quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTextField_name.setText("Search for drug you want to modify");
        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
        });

        jLabel_id.setText("The ID of the product is");

        jButton_update.setBackground(new java.awt.Color(0, 0, 0));
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sushil Shrestha\\Desktop\\Recurring Appointment_48px.png")); // NOI18N
        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jTextField_id.setEditable(false);

        jTextField_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rateActionPerformed(evt);
            }
        });
        jTextField_rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_rateKeyTyped(evt);
            }
        });

        jLabel3.setText("Quantity");

        jComboBox_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        jComboBox_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_monthActionPerformed(evt);
            }
        });

        jLabel4.setText("Expiry Date");

        jLabel1.setText("Drug Name");

        jLabel2.setText("Rate");

        jComboBox_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jTextField_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_quantityKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_rate))
                            .addComponent(jLabel_id))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_update)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_id))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel5.setText("UPDATE");

        jButton_cancel.setBackground(new java.awt.Color(0, 0, 0));
        jButton_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sushil Shrestha\\Desktop\\Back_48px.png")); // NOI18N
        jButton_cancel.setText("Back");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(162, 162, 162)
                        .addComponent(jButton_cancel)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
        String tname=jTextField_name.getText();
        if(!tname.equals("")){
         

        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from drug where name=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,tname);
            ResultSet rs=pst.executeQuery();
            while (rs.next()) {
                
                jTextField_id.setText(rs.getString(1));
                
                jTextField_quantity.setText(rs.getString(4));
                jTextField_rate.setText(rs.getString(3));
                jComboBox_month.setSelectedItem(rs.getString(5));
                jComboBox_year.setSelectedItem(rs.getString(6));
         
            }
            con.close();
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        }
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextField_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rateActionPerformed

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                jTextField_name.setText(jTextField_name.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                    String txt=jTextField_name.getText();
                    autocomplete(txt);
                    
            }
       
        });
        }
        
    }//GEN-LAST:event_jTextField_nameKeyPressed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
        MainframeAdmin m=new MainframeAdmin();
            m.setTitle("Medical Store Management");
            m.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jComboBox_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_monthActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jTextField_id.getText());
        String name=jTextField_name.getText();
        double rate =Double.parseDouble(jTextField_rate.getText());
        
        int qty=Integer.parseInt(jTextField_quantity.getText() );
        String exp_month=jComboBox_month.getSelectedItem().toString();
        String exp_year=jComboBox_year.getSelectedItem().toString();
        if(jTextField_name.getText().equals("")||jTextField_rate.getText().equals("")||jTextField_quantity.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Incomplete Data.");
        }else{
            int p=JOptionPane.showConfirmDialog(null,"Do you really want to modify the drug details?","Modify",JOptionPane.YES_NO_OPTION);
        if (p==0){
            try{
                Connection con=DBConnection.getConnection();
                String sql="update drug set name=?,rate=?,qty=?,exp_month=?,exp_year=?,sample_month=? where id=?";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,name);
                pst.setDouble(2,rate);
                pst.setInt(3,qty);
                pst.setString(4, exp_month);
                pst.setString(5,exp_year);
                pst.setInt(7,id);
                
            if(exp_month.equals("Jan"))
        {
            
            pst.setString(6, "1");
            
        }
        else if(exp_month.equals("Feb"))
        {
            
            pst.setString(6, "2");
            
        }
        else if(exp_month.equals("March"))
        {pst.setString(6, "3");}
        else if(exp_month.equals("April"))
            {pst.setString(6, "4");}
        else if(exp_month.equals("May"))
         {pst.setString(6, "5");}
        else if(exp_month.equals("June"))
            {pst.setString(6, "6");}
        else if(exp_month.equals("July"))
            {pst.setString(6, "7");}
        else if(exp_month.equals("Aug"))
         {pst.setString(6, "8");}
        else if(exp_month.equals("Sept"))
            {pst.setString(6, "9");}
        else if(exp_month.equals("Oct"))
         {pst.setString(6, "10");}
        else if(exp_month.equals("Nov"))
            {pst.setString(6, "11");}
        else if(exp_month.equals("Dec"))
         {pst.setString(6, "12");}
            pst.executeUpdate();
                con.close();
                

            } catch (Exception ex) {
                System.out.println(ex);
            }
        
        
        System.out.println("Changed");
        //clear all fields
        clearFields();
        JOptionPane.showMessageDialog(null,"Change saved.");
    }//GEN-LAST:event_jButton_updateActionPerformed
        }
    }
    
    private void jTextField_quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_quantityKeyTyped
        // TODO add your handling code here:
                char ch=evt.getKeyChar();
        if(!(ch>='0' && ch<='9')){
            evt.consume();

    }//GEN-LAST:event_jTextField_quantityKeyTyped
}
    private void jTextField_rateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rateKeyTyped
        // TODO add your handling code here:
                char ch=evt.getKeyChar();
        if(!(ch>='0' && ch<='9')){
            evt.consume();

    }//GEN-LAST:event_jTextField_rateKeyTyped
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox jComboBox_month;
    private javax.swing.JComboBox jComboBox_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_quantity;
    private javax.swing.JTextField jTextField_rate;
    // End of variables declaration//GEN-END:variables
    public void databasenama() {
         
        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from drug";
            Statement st=con.createStatement();
            if(con!=null)
            {
                System.out.println("Connection Sucessful");
            }
            else
                System.out.println("Connection failed");
            ResultSet rs=st.executeQuery(sql);
            while (rs.next()) {
                String nama=rs.getString("name");
                 
                name.add(nama);
            }
            rs.close();
                    
            con.close();
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }


         }
    public void autocomplete(String txt){
        String complete= " ";
        int start=txt.length();
        int last=txt.length();
        int a;
        for(a=0;a<name.size();a++){
            if(name.get(a).toString().startsWith(txt)){
                complete=name.get(a).toString();
                last=complete.length();
                break;
            }
    }
        if(last>start){
            jTextField_name.setText(complete);
            jTextField_name.setCaretPosition(last);
            jTextField_name.moveCaretPosition(start);
        }
        
    }
        
}

